# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/test2.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12protos/test2.proto\"\x17\n\x06Number\x12\r\n\x05value\x18\x01 \x01(\x02\x32t\n\nCalculator\x12 \n\nSquareRoot\x12\x07.Number\x1a\x07.Number\"\x00\x12\x1e\n\x08\x41\x64\x64ition\x12\x07.Number\x1a\x07.Number\"\x00\x12$\n\x0eMultiplication\x12\x07.Number\x1a\x07.Number\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.test2_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NUMBER._serialized_start=22
  _NUMBER._serialized_end=45
  _CALCULATOR._serialized_start=47
  _CALCULATOR._serialized_end=163
# @@protoc_insertion_point(module_scope)
